### ISSUE TITLE
dataset not available

### ISSUE THREAD

**Issue by lwmlyy** [chiahsuan156/KaggleDBQA#1]
The dataset link provided in https://www.microsoft.com/en-us/research/publication/kaggledbqa-realistic-evaluation-of-text-to-sql-parsers/ is not reachable. Is there any other links?

**Comment by lwmlyy** [comment]
@chiahsuan156

**Comment by chiahsuan156** [comment]
Hi, thanks for your interest!  Unfortunately, we no longer have access to the Microsoft page. That website appears to be down.
